version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hmt_user
      POSTGRES_PASSWORD: local_dev_password
      POSTGRES_DB: hmt_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hmt_user -d hmt_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://hmt_user:local_dev_password@postgres:5432/hmt_platform
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ENVIRONMENT: development
      FIREBASE_SERVICE_ACCOUNT: /app/firebase-key.json
    volumes:
      - ./backend:/app
      - ./firebase-key.json:/app/firebase-key.json
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_FIREBASE_CONFIG=${FIREBASE_CONFIG}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data: